In [24]:
from __future__ import division
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score,roc_auc_score

from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier

from xgboost.sklearn import XGBClassifier

import seaborn as sns
import matplotlib.pyplot as plt
#from analytics_tools.analytics_tools3 import freq_discrete
%matplotlib inline

In [25]:
def metricas(model,Xt,Xv,yt,yv):
    print "Accuracy_Train %.2f, Accuracy_Validate %.2f "%(accuracy_score(y_pred=model.predict(Xt),y_true=yt),accuracy_score(y_pred=model.predict(Xv),y_true=yv))
    print "ROC_Train %.2f, ROC_Validate %.2f "%(roc_auc_score(y_score=model.predict_proba(Xt)[:,1],y_true=yt),roc_auc_score(y_score=model.predict_proba(Xv)[:,1],y_true=yv))

In [26]:
df = pd.read_excel('Data/churn.xlsx')

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2801 entries, 0 to 2800
Data columns (total 14 columns):
V_ACCT_LGHT      2801 non-null int64
C_IP             2801 non-null object
C_VMP            2801 non-null object
V_N_VM_MESS      2801 non-null int64
V_T_DAY_CHG      2801 non-null float64
V_T_EVE_CALLS    2801 non-null int64
V_T_EVE_CHG      2801 non-null float64
V_T_NIG_CALLS    2801 non-null int64
V_T_NIG_CHG      2801 non-null float64
V_T_INT_CALLS    2801 non-null int64
V_T_INT_CHG      2801 non-null float64
V_CS_CALLS       2801 non-null int64
TARGET           2801 non-null int64
ID               2801 non-null int64
dtypes: float64(4), int64(8), object(2)
memory usage: 306.4+ KB

In [28]:
df.head()

,V_ACCT_LGHT,C_IP,C_VMP,V_N_VM_MESS,V_T_DAY_CHG,V_T_EVE_CALLS,V_T_EVE_CHG,V_T_NIG_CALLS,V_T_NIG_CHG,V_T_INT_CALLS,V_T_INT_CHG,V_CS_CALLS,TARGET,ID
0,128,No,Yes,25,45.07,99,16.78,91,11.01,3,2.70,1,0,1
1,107,No,Yes,26,27.47,103,16.62,103,11.45,3,3.70,1,0,2
2,137,No,No,0,41.38,110,10.30,104,7.32,5,3.29,0,0,3
3,65,No,No,0,21.95,83,19.42,111,9.40,6,3.43,4,1,11
4,168,No,No,0,21.90,71,8.92,128,6.35,2,3.02,1,0,13

In [29]:
var_disc = [v for v in df.columns if v[:2]=='C_']
var_cont = [v for v in df.columns if v[:2]=='V_']

for v in var_disc:
    df[v] = (df[v]=='Yes').astype(int)

In [31]:
df.head()

,V_ACCT_LGHT,C_IP,C_VMP,V_N_VM_MESS,V_T_DAY_CHG,V_T_EVE_CALLS,V_T_EVE_CHG,V_T_NIG_CALLS,V_T_NIG_CHG,V_T_INT_CALLS,V_T_INT_CHG,V_CS_CALLS,TARGET,ID
0,128,0,1,25,45.07,99,16.78,91,11.01,3,2.70,1,0,1
1,107,0,1,26,27.47,103,16.62,103,11.45,3,3.70,1,0,2
2,137,0,0,0,41.38,110,10.30,104,7.32,5,3.29,0,0,3
3,65,0,0,0,21.95,83,19.42,111,9.40,6,3.43,4,1,11
4,168,0,0,0,21.90,71,8.92,128,6.35,2,3.02,1,0,13

In [32]:
X = df[var_cont+var_disc].copy()
y = df['TARGET'].copy()

In [33]:
scaler = MinMaxScaler()
scaler.fit(X)
Xs = pd.DataFrame(scaler.transform(X),columns=X.columns)

In [34]:
Xs.head()

,V_ACCT_LGHT,V_N_VM_MESS,V_T_DAY_CHG,V_T_EVE_CALLS,V_T_EVE_CHG,V_T_NIG_CALLS,V_T_NIG_CHG,V_T_INT_CALLS,V_T_INT_CHG,V_CS_CALLS,C_IP,C_VMP
0,0.633880,0.581395,0.841885,0.489362,0.492640,0.377778,0.693383,0.166667,0.500000,0.166667,0.0,1.0
1,0.519126,0.604651,0.433248,0.531915,0.484789,0.511111,0.734390,0.166667,0.776243,0.166667,0.0,1.0
2,0.683060,0.000000,0.756211,0.606383,0.174681,0.522222,0.349487,0.333333,0.662983,0.000000,0.0,0.0
3,0.289617,0.000000,0.305085,0.319149,0.622179,0.600000,0.543336,0.416667,0.701657,0.666667,0.0,0.0
4,0.852459,0.000000,0.303924,0.191489,0.106968,0.788889,0.259087,0.083333,0.588398,0.166667,0.0,0.0

In [35]:
Xt,Xv,yt,yv = train_test_split(Xs,y,train_size=0.7)

In [36]:
modelo1 = MLPClassifier(activation='relu', alpha=0.00030000000000000003,
       batch_size='auto', beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(26, 30, 27),
       learning_rate='constant', learning_rate_init=0.001, max_iter=2000,
       momentum=0.9, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

modelo2 = SVC(C=1.0, cache_size=200, class_weight=None, coef0=2,
  decision_function_shape='ovo', degree=4, gamma=0.8000000000000003,
  kernel='rbf', max_iter=-1, probability=True, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [37]:
lst_model = [BaggingClassifier(),
             RandomForestClassifier(),
             AdaBoostClassifier(),
             XGBClassifier(),
             VotingClassifier(estimators=[('ANN',modelo1),('SVM',modelo2)],voting='soft')]

In [38]:
%%time
for model in lst_model:
    model.fit(Xt,yt)
    print metricas(model,Xt,Xv,yt,yv)

Accuracy_Train 0.99, Accuracy_Validate 0.95
ROC_Train 1.00, ROC_Validate 0.93
None
Accuracy_Train 0.99, Accuracy_Validate 0.94
ROC_Train 1.00, ROC_Validate 0.90
None
Accuracy_Train 0.91, Accuracy_Validate 0.89
ROC_Train 0.92, ROC_Validate 0.85
None
Accuracy_Train 0.97, Accuracy_Validate 0.95
ROC_Train 0.97, ROC_Validate 0.93
None

/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:171: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:171: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:171: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py:171: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

Accuracy_Train 0.94, Accuracy_Validate 0.91
ROC_Train 0.92, ROC_Validate 0.91
None
CPU times: user 2.66 s, sys: 687 ms, total: 3.35 s
Wall time: 2.51 s